
import './globals.css'
import NavBar from './Components/NavBar';

export const metadata = {
  title: 'Resume Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><NavBar/>{children}</body>
    </html>
  )
}
